Repository mipengine/mip2-extensions, pull requests merged in 2019-01, with the labels that each got.

#412 feat：添加微信ua识别，去除对dp的iframe限制
  components/mip-env/README.md
  components/mip-env/example/mip-env.html
  components/mip-env/mip-env.js
Labels: enhancement

#432 feat: 迁移 mip-install-serviceworker
  components/mip-install-serviceworker/README.md
  components/mip-install-serviceworker/example/install.html
  components/mip-install-serviceworker/example/mip-install-serviceworker.html
  components/mip-install-serviceworker/example/shell.html
  components/mip-install-serviceworker/example/sw.js
  components/mip-install-serviceworker/install-url-rewiter.js
  components/mip-install-serviceworker/mip-install-serviceworker.js
  components/mip-install-serviceworker/util.js
Labels: reviewing

#460 feat: 迁移 mip-form
  components/mip-form/README.md
  components/mip-form/example/mip-form.html
  components/mip-form/mip-form-fn.js
  components/mip-form/mip-form.js
Labels: reviewing

#452 feat: 迁移 mip-appdl
  components/mip-appdl/README.md
  components/mip-appdl/example/mip-appdl.html
  components/mip-appdl/mip-appdl.js
  components/mip-appdl/mip-appdl.less
Labels: reviewing

#416 feat: 迁移 mip-bridge-baidu
  components/mip-bridge-baidu/README.md
  components/mip-bridge-baidu/example/mip-bridge-baidu.html
  components/mip-bridge-baidu/mip-bridge-baidu.js
Labels: reviewing

#457 feat: 迁移 mip-vd-tabs
  components/mip-vd-tabs/README.md
  components/mip-vd-tabs/example/index.html
  components/mip-vd-tabs/example/index2.html
  components/mip-vd-tabs/example/index3.html
  components/mip-vd-tabs/example/index4.html
  components/mip-vd-tabs/example/index5.html
  components/mip-vd-tabs/mip-vd-tabs.js
  components/mip-vd-tabs/mip-vd-tabs.less
  components/mip-vd-tabs/tab.js
Labels: reviewing

#438 feat: 迁移 mip-vd-baidu
  components/mip-vd-baidu/README.md
  components/mip-vd-baidu/example/index.html
  components/mip-vd-baidu/mip-vd-baidu.js
Labels: reviewing

#455 feat: 迁移 mip-widget-full-height
  components/mip-widget-full-height/README.md
  components/mip-widget-full-height/example/index.html
  components/mip-widget-full-height/mip-widget-full-height.js
Labels: reviewing

#443 feat: 迁移 mip-filter
  components/mip-filter/README.md
  components/mip-filter/example/mip-filter.html
  components/mip-filter/mip-filter.js
Labels: reviewing

#447 feat: 迁移 mip-map
  components/mip-map/README.md
  components/mip-map/example/mip-map.html
  components/mip-map/mip-map.js
  components/mip-map/mip-map.less
  components/mip-map/mip-map.vue
Labels: reviewing

#448 feat: 迁移 mip-link
  components/mip-link/README.md
  components/mip-link/example/mip-link.html
  components/mip-link/mip-link.js
  components/mip-link/mip-link.vue
Labels: reviewing

#423 feat: 迁移 mip-list
  components/mip-list/README.md
  components/mip-list/example/data-has-more.js
  components/mip-list/example/data.js
  components/mip-list/example/mip-list.html
  components/mip-list/mip-list.js
Labels: reviewing

#450 feat: 迁移 mip-gototop
  components/mip-gototop/README.md
  components/mip-gototop/example/mip-gototop1.html
  components/mip-gototop/example/mip-gototop2.html
  components/mip-gototop/mip-gototop.js
  components/mip-gototop/mip-gototop.less
  components/mip-gototop/mip-gototop.vue
Labels: reviewing

#424 feat: mip-stats-baidu 组件迁移
  components/mip-stats-baidu/README.md
  components/mip-stats-baidu/example/mip-stats-baidu-attr.html
  components/mip-stats-baidu/example/mip-stats-baidu-json.html
  components/mip-stats-baidu/mip-stats-baidu.js
Labels: reviewing

#434 feat: mip-nav-slidedown 组件迁移
  components/mip-nav-slidedown/README.md
  components/mip-nav-slidedown/mip-nav-slidedown.js
  components/mip-nav-slidedown/mip-nav-slidedown.less
Labels: reviewing

#429 feat: 迁移 mip-showmore
  components/mip-showmore/README.md
  components/mip-showmore/example/click.html
  components/mip-showmore/example/click2.html
  components/mip-showmore/example/custom.html
  components/mip-showmore/example/doNotToggle.html
  components/mip-showmore/example/mip-showmore.html
  components/mip-showmore/mip-showmore.js
  components/mip-showmore/mip-showmore.less
Labels: reviewing

#431 feat: 迁移 mip-mustache
  components/mip-image-slider/test/mip-image-slider.spec.js
  components/mip-mustache/README.md
  components/mip-mustache/example/mip-mustache.html
  components/mip-mustache/html-sanitizer.js
  components/mip-mustache/mip-mustache.js
  components/mip-mustache/sanitizer.js
  package.json
Labels: reviewing

#453 feat: 迁移 mip-app-banner
  components/mip-app-banner/README.md
  components/mip-app-banner/example/mip-app-banner.html
  components/mip-app-banner/mip-app-banner.js
  components/mip-app-banner/mip-app-banner.less
Labels: reviewing

#421 更新 mip-semi-fixed
  components/mip-semi-fixed/README.md
  components/mip-semi-fixed/example/mip-semi-fixed.html
  components/mip-semi-fixed/mip-semi-fixed.js
Labels: reviewing

#444 feat: 迁移 mip-history
  components/mip-history/README.md
  components/mip-history/example/mip-history.html
  components/mip-history/mip-history.js
  components/mip-history/mip-history.less
Labels: reviewing

#422 feat: mip-analytics 组件迁移
  components/mip-analytics/README.md
  components/mip-analytics/example/mip-analytics.html
  components/mip-analytics/mip-analytics.js
Labels: reviewing

#435 feat: mip-scrollbox 组件迁移
  components/mip-scrollbox/README.md
  components/mip-scrollbox/example/index.html
  components/mip-scrollbox/mip-scrollbox.js
  components/mip-scrollbox/mip-scrollbox.less
  package.json
Labels: reviewing

#427 feat: mip-stats-cnzz 组件迁移
  components/mip-stats-cnzz/README.md
  components/mip-stats-cnzz/example/index.html
  components/mip-stats-cnzz/mip-stats-cnzz.js
Labels: reviewing

#440 feat: mip-ad-ecom 组件迁移
  components/mip-ad-ecom/README.md
  components/mip-ad-ecom/data.js
  components/mip-ad-ecom/dom.js
  components/mip-ad-ecom/example/index.html
  components/mip-ad-ecom/example/mock.json
  components/mip-ad-ecom/mip-ad-ecom.js
  components/mip-ad-ecom/mip-ad-ecom.less
  components/mip-ad-ecom/pmd.less
  components/mip-ad-ecom/url.js
Labels: reviewing

#458 feat: 迁移 mip-access
  components/mip-access/README.md
  components/mip-access/example/authorization.json
  components/mip-access/example/mip-access.html
  components/mip-access/expr-impl.jison
  components/mip-access/expr-impl.js
  components/mip-access/expr.js
  components/mip-access/md5.js
  components/mip-access/mip-access.js
  components/mip-access/mip-access.less
  components/mip-access/mip-login.js
Labels: reviewing

#459 feat: 迁移 mip-login-done
  components/mip-login-done/README.md
  components/mip-login-done/example/mip-login-done.html
  components/mip-login-done/mip-login-done.html
  components/mip-login-done/mip-login-done.js
Labels: reviewing

#433 feat: mip-accordion 组件迁移
  components/mip-accordion/README.md
  components/mip-accordion/mip-accordion.js
Labels: reviewing

#417 feat: 迁移 mip-ad 组件
  components/mip-ad/README.md
  components/mip-ad/example/mip-ad-baidu.html
  components/mip-ad/example/mip-ad-baidussp.html
  components/mip-ad/example/mip-ad-comm.html
  components/mip-ad/example/mip-ad-qwang.html
  components/mip-ad/example/mip-ad-ssp.html
  components/mip-ad/example/mip-baidu-wm-ext.html
  components/mip-ad/mip-ad-baidu.js
  components/mip-ad/mip-ad-baidu.md
  components/mip-ad/mip-ad-baidussp.js
  components/mip-ad/mip-ad-baidussp.md
  components/mip-ad/mip-ad-comm.js
  components/mip-ad/mip-ad-comm.md
  components/mip-ad/mip-ad-imageplus.js
  components/mip-ad/mip-ad-qwang.js
  components/mip-ad/mip-ad-qwang.md
  components/mip-ad/mip-ad-ssp.js
  components/mip-ad/mip-ad-ssp.md
  components/mip-ad/mip-ad.js
  components/mip-ad/mip-ad.less
  components/mip-ad/mip-baidu-wm-ext.js
  components/mip-ad/mip-baidu-wm-ext.md
Labels: reviewing

#456 feat: 迁移 mip-group-selection
  components/mip-group-selection/README.md
  components/mip-group-selection/example/mip-group-selection1.html
  components/mip-group-selection/example/mip-group-selection2.html
  components/mip-group-selection/example/mip-group-selection3.html
  components/mip-group-selection/mip-group-selection.js
  components/mip-group-selection/mip-group-selection.less
Labels: reviewing

#465 feat: mip-share 组件迁移
  components/mip-share/README.md
  components/mip-share/example/fixed.html
  components/mip-share/example/index.html
  components/mip-share/example/user-define.html
  components/mip-share/mip-share.js
  components/mip-share/mip-share.less
  components/mip-share/share/share.js
  components/mip-share/share/shareConfig.js
  components/mip-share/share/wxSdk.min.js
Labels: reviewing

#478 fix：mip-vd-tabs 个别浏览器展现有误
  components/mip-vd-tabs/mip-vd-tabs.js
  components/mip-vd-tabs/tab.js
Labels: bug
